# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

1  User.create(username: "Allison", password: "password")
2  User.create(username: "Brian", password: "password")
3  User.create(username: "Cassie", password: "password")
4  User.create(username: "Doug", password: "password")

1  Author.create(name: "Leigh Bardugo") 1
2  Author.create(name: "Diana Gabaldon") 2
3  Author.create(name: "Maggie Stiefvater") 3
4  Author.create(name: "Ruth Ware") 4
5  Author.create(name: "Stephen King") 5
6  Author.create(name: "George R. R. Martin") 6
7  Author.create(name: "Patrick Rothfuss") 7
8  Author.create(name: "Naomi Novik") 8
9  Author.create(name: "Sarah J. Maas") 9

1  Genre.create(name: "YA Fantasy")
2  Genre.create(name: "Historical Romance")
3  Genre.create(name: "Mystery Thriller")
4  Genre.create(name: "Horror")
5  Genre.create(name: "Epic Fantasy")
6  Genre.create(name: "Western")
7  Genre.create(name: "Middle Grade Fantasy")

1  Book.create(title: "Six of Crows",  author_id: 1,  genre_id: 1,  page_count: 510)
2  Book.create(title: "Crooked Kingdom",  author_id: 1, genre_id:1,  page_count: 536)
3  Book.create(title: "Outlander",  author_id: 2,  genre_id: 2,  page_count: 850 )
4  Book.create(title: "The Raven Boys", author_id: 3, genre_id: 1,  page_count: 409)
5  Book.create(title: "The Lying Game", author_id: 4, genre_id: 3,  page_count: 370)
6  Book.create(title: "Insomnia", author_id: 5, genre_id: 4,  page_count: 890)
7  Book.create(title: "The Shining", author_id: 5, genre_id: 4, page_count: 447)
8  Book.create(title: "A Game of Thrones", author_id: 6, genre_id: 5, page_count: 848)
9  Book.create(title: "Uprooted", author_id: 8, genre_id: 1, page_count: 435)
10 Book.create(title: "The Sisters Brothers", author_id: 11, genre_id: 6, page_count: 328)
11 Book.create(title: "Throne of Glass", author_id: 9, genre_id: 1, page_count: 404)
12 Book.create(title: "A Court of Thorns and Roses", author_id: 9, genre_id: 1, page_count: 416)
13 Book.create(title: "The Name of the Wind", author_id: 7, genre_id: 5, page_count: 662)
14 Book.create(title: "Siege and Storm", author_id: 1, genre_id: 1, page_count: 435)

1  ReadStatus.create(value: false, user_id: 1, book_id: 1)
2  ReadStatus.create(value: false, user_id: 2, book_id: 2)
3  ReadStatus.create(value: false, user_id: 3, book_id: 3)
4  ReadStatus.create(value: false, user_id: 4, book_id: 4)
5  ReadStatus.create(value: false, user_id: 1, book_id: 5)
6  ReadStatus.create(value: false, user_id: 2, book_id: 6)
7  ReadStatus.create(value: false, user_id: 3, book_id: 7)
8  ReadStatus.create(value: false, user_id: 4, book_id: 8)
9  ReadStatus.create(value: true, user_id: 1, book_id: 9)
10 ReadStatus.create(value: true, user_id: 2, book_id: 10)
11 ReadStatus.create(value: true, user_id: 3, book_id: 11)
12 ReadStatus.create(value: true, user_id: 4, book_id: 12)
13 ReadStatus.create(value: true, user_id: 1, book_id: 13)
14 ReadStatus.create(value: true, user_id: 2, book_id: 14)
15 ReadStatus.create(value: true, user_id: 3, book_id: 1)
16 ReadStatus.create(value: true, user_id: 4, book_id: 2)
17 ReadStatus.create(value: true, user_id: 1, book_id: 3)
18 ReadStatus.create(value: true, user_id: 2, book_id: 4)
19 ReadStatus.create(value: true, user_id: 3, book_id: 5)
20 ReadStatus.create(value: true, user_id: 4, book_id: 6)
21 ReadStatus.create(value: true, user_id: 1, book_id: 7)
22 ReadStatus.create(value: true, user_id: 2, book_id: 8)
23 ReadStatus.create(value: true, user_id: 3, book_id: 9)
24 ReadStatus.create(value: true, user_id: 4, book_id: 10)
25 ReadStatus.create(value: true, user_id: 1, book_id: 11)
26 ReadStatus.create(value: true, user_id: 2, book_id: 12)
27 ReadStatus.create(value: true, user_id: 3, book_id: 13)
28 ReadStatus.create(value: true, user_id: 4, book_id: 14)
29 ReadStatus.create(value: true, user_id: 1, book_id: 12)
30 ReadStatus.create(value: true, user_id: 2, book_id: 11)

9  Review.create(content: "Brilliant.", user_id: 1, book_id: 9)
10 Review.create(content: "Loved it!", user_id: 2, book_id: 10)
11 Review.create(content: "A modern day classic.", user_id: 3, book_id: 11)
12 Review.create(content: "Didn't love it, didn't hate it.", user_id: 4, book_id: 12)
13 Review.create(content: "Meh.", user_id: 1, book_id: 13)
14 Review.create(content: "Just ok.", user_id: 2, book_id: 14)
15 Review.create(content: "Alright.", user_id: 3, book_id: 1)
16 Review.create(content: "So-so.", user_id: 4, book_id: 2)
17 Review.create(content: "Amazing!", user_id: 1, book_id: 3)
18 Review.create(content: "Best book I have ever read!", user_id: 2, book_id: 4)
19 Review.create(content: "A masterpiece!", user_id: 3, book_id: 5)
20 Review.create(content: "Pretty great!", user_id: 4, book_id: 6)
21 Review.create(content: "Worst book I have ever read in my life.", user_id: 1, book_id: 7)
22 Review.create(content: "Awful.", user_id: 2, book_id: 8)
23 Review.create(content: "Hated it!", user_id: 3, book_id: 9)
24 Review.create(content: "Terrible.", user_id: 4, book_id: 10)
25 Review.create(content: "Equal parts of everything I like!", user_id: 1, book_id: 11)
26 Review.create(content: "Good, not great.", user_id: 2, book_id: 12)
27 Review.create(content: "Bad, not awful.", user_id: 3, book_id: 13)
28 Review.create(content: "Would read again", user_id: 4, book_id: 14)
29 Review.create(content: "Couldn't stop reading!", user_id: 1, book_id: 12)
30 Review.create(content: "A new favorite!", user_id: 2, book_id: 11)

9  Rating.create(value: 4, user_id: 1, book_id: 9)
10 Rating.create(value: 5, user_id: 2, book_id: 10)
11 Rating.create(value: 5, user_id: 3, book_id: 11)
12 Rating.create(value: 3, user_id: 4, book_id: 12)
13 Rating.create(value: 3, user_id: 1, book_id: 13)
14 Rating.create(value: 3, user_id: 2, book_id: 14)
15 Rating.create(value: 3, user_id: 3, book_id: 1)
16 Rating.create(value: 2, user_id: 4, book_id: 2)
17 Rating.create(value: 5, user_id: 1, book_id: 3)
18 Rating.create(value: 5, user_id: 2, book_id: 4)
19 Rating.create(value: 5, user_id: 3, book_id: 5)
20 Rating.create(value: 4, user_id: 4, book_id: 6)
21 Rating.create(value: 1, user_id: 1, book_id: 7)
22 Rating.create(value: 1, user_id: 2, book_id: 8)
23 Rating.create(value: 2, user_id: 3, book_id: 9)
24 Rating.create(value: 2, user_id: 4, book_id: 10)
25 Rating.create(value: 5, user_id: 1, book_id: 11)
26 Rating.create(value: 4, user_id: 2, book_id: 12)
27 Rating.create(value: 2, user_id: 3, book_id: 13)
28 Rating.create(value: 4, user_id: 4, book_id: 14)
29 Rating.create(value: 5, user_id: 1, book_id: 12)
30 Rating.create(value: 5, user_id: 2, book_id: 11)
