# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "Allison", password: "password")
User.create(username: "Brian", password: "password")
User.create(username: "Cassie", password: "password")
User.create(username: "Doug", password: "password")

Author.create(name: "Leigh Bardugo")
Author.create(name: "Diana Gabaldon")
Author.create(name: "Maggie Stiefvater")
Author.create(name: "Ruth Ware")
Author.create(name: "Stephen King")
Author.create(name: "George R. R. Martin")
Author.create(name: "Patrick Rothfuss")
Author.create(name: "Naomi Novik")
Author.create(name: "Sarah J. Maas")

Genre.create(name: "YA Fantasy")
Genre.create(name: "Historical Romance")
Genre.create(name: "Mystery Thriller")
Genre.create(name: "Horror")
Genre.create(name: "Epic Fantasy")
Genre.create(name: "Western")

Book.create(title: "Six of Crows",  author_id: 1,  genre_id: 1,  page_count: 510)
Book.create(title: "Crooked Kingdom",  author_id: 1, genre_id:1,  page_count: 536)
Book.create(title: "Outlander",  author_id: 2,  genre_id: 2,  page_count: 850 )
Book.create(title: "The Raven Boys", author_id: 3, genre_id: 1,  page_count: 409)
Book.create(title: "The Lying Game", author_id: 4, genre_id: 3,  page_count: 370)
Book.create(title: "Insomnia", author_id: 5, genre_id: 4,  page_count: 890)
Book.create(title: "The Shining", author_id: 5, genre_id: 4, page_count: 447)
Book.create(title: "A Game of Thrones", author_id: 6, genre_id: 5, page_count: 848)
Book.create(title: "Uprooted", author_id: 8, genre_id: 1, page_count: 435)
Book.create(title: "The Sisters Brothers", author_id: 11, genre_id: 6, page_count: 328)
Book.create(title: "Throne of Glass", author_id: 9, genre_id: 1, page_count: 404)
Book.create(title: "A Court of Thorns and Roses", author_id: 9, genre_id: 1, page_count: 416)
Book.create(title: "The Name of the Wind", author_id: 7, genre_id: 5, page_count: 662)
Book.create(title: "Siege and Storm", author_id: 1, genre_id: 1, page_count: 435)

ReadStatus.create(value: false, user_id: 1, book_id: 1)
ReadStatus.create(value: false, user_id: 2, book_id: 2)
ReadStatus.create(value: false, user_id: 3, book_id: 3)
ReadStatus.create(value: false, user_id: 4, book_id: 4)
ReadStatus.create(value: false, user_id: 1, book_id: 5)
ReadStatus.create(value: false, user_id: 2, book_id: 6)
ReadStatus.create(value: false, user_id: 3, book_id: 7)
ReadStatus.create(value: false, user_id: 4, book_id: 8)
ReadStatus.create(value: true, user_id: 1, book_id: 9)
ReadStatus.create(value: true, user_id: 2, book_id: 10)
ReadStatus.create(value: true, user_id: 3, book_id: 11)
ReadStatus.create(value: true, user_id: 4, book_id: 12)
ReadStatus.create(value: true, user_id: 1, book_id: 13)
ReadStatus.create(value: true, user_id: 2, book_id: 14)
ReadStatus.create(value: true, user_id: 3, book_id: 1)
ReadStatus.create(value: true, user_id: 4, book_id: 2)
ReadStatus.create(value: true, user_id: 1, book_id: 3)
ReadStatus.create(value: true, user_id: 2, book_id: 4)
ReadStatus.create(value: true, user_id: 3, book_id: 5)
ReadStatus.create(value: true, user_id: 4, book_id: 6)
ReadStatus.create(value: true, user_id: 1, book_id: 7)
ReadStatus.create(value: true, user_id: 2, book_id: 8)
ReadStatus.create(value: true, user_id: 3, book_id: 9)
ReadStatus.create(value: true, user_id: 4, book_id: 10)
ReadStatus.create(value: true, user_id: 1, book_id: 11)
ReadStatus.create(value: true, user_id: 2, book_id: 12)
ReadStatus.create(value: true, user_id: 3, book_id: 13)
ReadStatus.create(value: true, user_id: 4, book_id: 14)
ReadStatus.create(value: true, user_id: 1, book_id: 12)
ReadStatus.create(value: true, user_id: 2, book_id: 11)

Review.create(content: "Brilliant.", user_id: 1, book_id: 9)
Review.create(content: "Loved it!", user_id: 2, book_id: 10)
Review.create(content: "A modern day classic.", user_id: 3, book_id: 11)
Review.create(content: "Didn't love it, didn't hate it.", user_id: 4, book_id: 12)
Review.create(content: "Meh.", user_id: 1, book_id: 13)
Review.create(content: "Just ok.", user_id: 2, book_id: 14)
Review.create(content: "Alright.", user_id: 3, book_id: 1)
Review.create(content: "So-so.", user_id: 4, book_id: 2)
Review.create(content: "Amazing!", user_id: 1, book_id: 3)
Review.create(content: "Best book I have ever read!", user_id: 2, book_id: 4)
Review.create(content: "A masterpiece!", user_id: 3, book_id: 5)
Review.create(content: "Pretty great!", user_id: 4, book_id: 6)
Review.create(content: "Worst book I have ever read in my life.", user_id: 1, book_id: 7)
Review.create(content: "Awful.", user_id: 2, book_id: 8)
Review.create(content: "Hated it!", user_id: 3, book_id: 9)
Review.create(content: "Terrible.", user_id: 4, book_id: 10)
Review.create(content: "Equal parts of everything I like!", user_id: 1, book_id: 11)
Review.create(content: "Good, not great.", user_id: 2, book_id: 12)
Review.create(content: "Bad, not awful.", user_id: 3, book_id: 13)
Review.create(content: "Would read again", user_id: 4, book_id: 14)
Review.create(content: "Couldn't stop reading!", user_id: 1, book_id: 12)
Review.create(content: "A new favorite!", user_id: 2, book_id: 11)

Rating.create(value: 4, user_id: 1, book_id: 9)
Rating.create(value: 5, user_id: 2, book_id: 10)
Rating.create(value: 5, user_id: 3, book_id: 11)
Rating.create(value: 3, user_id: 4, book_id: 12)
Rating.create(value: 3, user_id: 1, book_id: 13)
Rating.create(value: 3, user_id: 2, book_id: 14)
Rating.create(value: 3, user_id: 3, book_id: 1)
Rating.create(value: 2, user_id: 4, book_id: 2)
Rating.create(value: 5, user_id: 1, book_id: 3)
Rating.create(value: 5, user_id: 2, book_id: 4)
Rating.create(value: 5, user_id: 3, book_id: 5)
Rating.create(value: 4, user_id: 4, book_id: 6)
Rating.create(value: 1, user_id: 1, book_id: 7)
Rating.create(value: 1, user_id: 2, book_id: 8)
Rating.create(value: 2, user_id: 3, book_id: 9)
Rating.create(value: 2, user_id: 4, book_id: 10)
Rating.create(value: 5, user_id: 1, book_id: 11)
Rating.create(value: 4, user_id: 2, book_id: 12)
Rating.create(value: 2, user_id: 3, book_id: 13)
Rating.create(value: 4, user_id: 4, book_id: 14)
Rating.create(value: 5, user_id: 1, book_id: 12)
Rating.create(value: 5, user_id: 2, book_id: 11)
